language: python
python:
    - '3.6'
install:
install:
  - 'pip install pytest-cov'
  - 'pip install coveralls'
  - 'pip install pipenv'
  - 'pipenv install'
script: pytest
after_success:
  - coveralls
